######################################################################
# GitLab CI build script for the Kafka WebSocket Proxy               #
######################################################################
#image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.13_jdk11

variables:
  CI: "true"
  DOCKER_DRIVER: overlay
  # Setting specific folder for sbt-coursier to cache artifacts
  COURSIER_CACHE: "/root/cache/coursier"
  # Container scanning properties
  CS_MAJOR_VERSION: 2
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/server
  CI_APPLICATION_TAG: $CI_COMMIT_SHA
  # Static Application Security Testing properties
  SAST_JAVA_VERSION: 11
  SAST_EXCLUDED_PATHS: "target, */target, */src/test, website"
  SAST_DEFAULT_ANALYZERS: "spotbugs, kubesec, mobsf"
  SAST_EXCLUDED_ANALYZERS: "eslint, nodejs-scan"
  # Dependency scan properties
  DS_DEFAULT_ANALYZERS: "gemnasium-maven"
  # Flag to trigger manual publishing of pages
  MANUAL_PUBLISH_PAGES: "false"

cache:
  untracked: true
  paths:
    - cache

stages:
  - build
  - test
  - publish-docker
  - deploy
  - scan

include:
  - local: "/.gitlab/build_templates/gitlab-ci-scala-build.yml"
    rules:
      - if: '$MANUAL_PUBLISH_PAGES != "true"'
  - local: "/.gitlab/build_templates/gitlab-ci-scala-docker.yml"
    rules:
      - if: '$MANUAL_PUBLISH_PAGES != "true"'
  - local: "/.gitlab/build_templates/gitlab-ci-scala-pages.yml"
  - local: "/.gitlab/build_templates/gitlab-ci-project-scanning.yml"
    rules:
      - if: '$MANUAL_PUBLISH_PAGES != "true"'