################################################################################
# GitLab pages pipeline
################################################################################
variables:
  CI: "true"
  DOCKER_DRIVER: overlay
  SBT_MDOCS_MODULE_DIR: '$CI_PROJECT_NAME-docs'

.shared_rules:
  rules:
    # Execute only when a tag is starting with v followed by a digit
    - if: $CI_COMMIT_TAG =~ /^v\d.*/

pages:build:
  rules:
    - !reference [.shared_rules, rules]
  stage: build
  image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.13_jdk11
  tags:
    - docker
  script:
    - sbt docs/mdoc
  artifacts:
    paths:
      - $SBT_MDOCS_MODULE_DIR/target
      - website

pages:
  rules:
    - !reference [.shared_rules, rules]
  stage: deploy
  image: node:15.12-alpine3.13
  dependencies:
    - pages:build
  script:
    - cd website
    - yarn install
    - yarn build
    - mv ./build ../public
  artifacts:
    paths:
      - public
