apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: kafka-websocket-proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: kafka-websocket-proxy
