apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: kafka-websocket-proxy
spec:
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka-websocket-proxy
  template:
    metadata:
      labels:
        app: kafka-websocket-proxy
    spec:
      containers:
        - name: kafka-websocket-proxy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: WSPROXY_SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WSPROXY_KAFKA_BOOTSTRAP_HOSTS
              value: "{{ .Values.env.WSPROXY_KAFKA_BOOTSTRAP_HOSTS }}"
            - name: WSPROXY_KAFKA_PRODUCER_COMPRESSION_TYPE
              value: "{{ .Values.env.WSPROXY_KAFKA_PRODUCER_COMPRESSION_TYPE }}"
            - name: WSPROXY_CH_MAX_STACK_SIZE
              value: "{{ .Values.env.WSPROXY_CH_MAX_STACK_SIZE }}"
            - name: WSPROXY_CH_AUTOCOMMIT_ENABLED
              value: "{{ .Values.env.WSPROXY_CH_AUTOCOMMIT_ENABLED }}"
            - name: WSPROXY_SECURE_HEALTHCHECK_ENDPOINT
              value: "{{ .Values.env.WSPROXY_SECURE_HEALTHCHECK_ENDPOINT }}"
            - name: WSPROXY_BASIC_AUTH_ENABLED
              value: "{{ .Values.env.WSPROXY_BASIC_AUTH_ENABLED }}"
            - name: WSPROXY_BASIC_AUTH_USERNAME
              value: "{{ .Values.env.WSPROXY_BASIC_AUTH_USERNAME }}"
            - name: WSPROXY_BASIC_AUTH_PASSWORD
              value: "{{ .Values.env.WSPROXY_BASIC_AUTH_PASSWORD }}"
            - name: WSPROXY_BASIC_AUTH_REALM
              value: "{{ .Values.env.WSPROXY_BASIC_AUTH_REALM }}"
            # Add additional container configuration here if needed
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
