---
version: '3'

networks:
  kafka_dev_sandbox:
    driver: bridge

services:
  # Confluent Control Center
  control-center:
    image: confluentinc/cp-enterprise-control-center:${CONFLUENT_VERESION}
    hostname: control-center
    container_name: control-center
    links:
      - zookeeper
      - kafka1
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka1:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONTROL_CENTER_CONNECT_CLUSTER: http://connect:8083
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    extra_hosts:
      - "moby:127.0.0.1"
    networks:
      - kafka_dev_sandbox
    labels:
      kafka.sandbox.container.type: "control-center"
